language: node_js

node_js:
- nodejs
- '8'
cache:
  directories:
  - node_modules
install:
- npm install

script:
- npm run build

before_install:
- openssl aes-256-cbc -K $encrypted_f812e1a00ef1_key -iv $encrypted_f812e1a00ef1_iv
  -in QCloud_CVM.enc -out QCloud_CVM -d

addons:
- ssh_known_hosts: 115.159.209.131

before_deploy:
- openssl aes-256-cbc -K $encrypted_f812e1a00ef1_key -iv $encrypted_f812e1a00ef1_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -rv --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* root@115.159.209.131:/www/wwwroot/music.io-code.com
    - echo -e "\033[32m 已同步到网站 \033[0m"
  on:
    branch: v2-beta
